[versions]
kotlin = "2.1.21"
toolchain = "21"
shadow = "8.3.8"
sentry = "8.17.0"
log4j = "2.25.0"
slf4j = "2.0.17"
configurate = "4.1.2"
cloud = "2.0.0"
cloud-minecraft = "2.0.0-beta.10"
adventure = "4.22.0"
tokenReplacer = "1.1.7"
paper-api = "1.21-R0.1-SNAPSHOT"
velocity-api = "3.4.0-SNAPSHOT"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
tokenReplacer = { id = "net.raphimc.class-token-replacer", version.ref = "tokenReplacer" }

[libraries]
# Logging
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

# Configurate
configurate-bom = { group = "org.spongepowered", name = "configurate-bom", version.ref = "configurate" }
configurate-hocon = { group = "org.spongepowered", name = "configurate-hocon" }
configurate-extra-kotlin = { group = "org.spongepowered", name = "configurate-extra-kotlin" }

# Cloud
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud" }
cloud-kotlin-extensions = { group = "org.incendo", name = "cloud-kotlin-extensions", version.ref = "cloud" }
cloud-minecraft-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloud-minecraft" }
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud-minecraft" }
cloud-velocity = { group = "org.incendo", name = "cloud-velocity", version.ref = "cloud-minecraft" }

# Adventure
adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

# Api
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity-api" }

# Required
sentry-log4j2 = { group = "io.sentry", name = "sentry-log4j2", version.ref = "sentry" }
